# GoReleaser v2 configuration
version: 2

project_name: harlequin

# Note: For monorepo support, run from root with:
# goreleaser release --config cli/.goreleaser.yaml

# Environment variables
env:
  - CGO_ENABLED=0

# Output directory (relative to workspace root)
dist: ../dist

# Build configuration
builds:
  - id: harlequin
    main: ./main.go
    binary: harlequin
    
    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    
    # All combinations are supported
    # Windows 11 runs on ARM64 (Surface Pro X, etc.)
    
    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser
    
    # Custom binary naming
    hooks:
      pre:
        - go mod tidy
        - go generate ./...

# Archive configuration
archives:
  - id: harlequin
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - README.md

# Checksum
checksum:
  name_template: 'checksums.txt'

# Snapshot
snapshot:
  version_template: "{{ incpatch .Version }}-next"

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

# Skip GitHub Release (handled by Nx Release)
release:
  disable: true

