# GoReleaser v2 configuration for Remote Signing Server
version: 2

project_name: harlequin-remote-signing

# Note: For monorepo support, run from root with:
# goreleaser release --config remote-signing/.goreleaser.yaml

# Environment variables
env:
  - CGO_ENABLED=0

# Output directory (relative to workspace root)
dist: ../dist/remote-signing

# Build configuration
builds:
  - id: remote-signing
    main: ./cmd/remote-signing
    binary: harlequin-remote-signing

    # Build for multiple platforms
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64

    # Build flags
    flags:
      - -trimpath
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
      - -X main.builtBy=goreleaser

    # Custom binary naming
    hooks:
      pre:
        - go mod tidy
        - go generate ./...

# Archive configuration
archives:
  - id: remote-signing
    name_template: '{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}'
    files:
      - README.md
      - config.example.json
      - templates/**/*

# Checksum
checksum:
  name_template: 'checksums.txt'

# Snapshot
snapshot:
  version_template: '{{ incpatch .Version }}-next'

# Changelog
changelog:
  sort: asc
  use: github
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - '^ci:'
  groups:
    - title: Features
      regexp: "^.*feat[(\\w)]*:+.*$"
      order: 0
    - title: 'Bug fixes'
      regexp: "^.*fix[(\\w)]*:+.*$"
      order: 1
    - title: Others
      order: 999

# Docker images (multi-arch builds)
dockers:
  - image_templates:
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:{{.Version}}-amd64'
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:latest-amd64'
    dockerfile: Dockerfile.binary
    use: buildx
    build_flag_templates:
      - --platform=linux/amd64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description=Harlequin Remote Signing Server
      - --label=org.opencontainers.image.url=https://github.com/the-permaweb-harlequin/harlequin-toolkit
      - --label=org.opencontainers.image.source=https://github.com/the-permaweb-harlequin/harlequin-toolkit
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT
    extra_files:
      - templates/
      - config.example.json

  - image_templates:
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:{{.Version}}-arm64'
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:latest-arm64'
    dockerfile: Dockerfile.binary
    use: buildx
    build_flag_templates:
      - --platform=linux/arm64
      - --label=org.opencontainers.image.title={{.ProjectName}}
      - --label=org.opencontainers.image.description=Harlequin Remote Signing Server
      - --label=org.opencontainers.image.url=https://github.com/the-permaweb-harlequin/harlequin-toolkit
      - --label=org.opencontainers.image.source=https://github.com/the-permaweb-harlequin/harlequin-toolkit
      - --label=org.opencontainers.image.version={{.Version}}
      - --label=org.opencontainers.image.created={{.Date}}
      - --label=org.opencontainers.image.revision={{.FullCommit}}
      - --label=org.opencontainers.image.licenses=MIT
    extra_files:
      - templates/
      - config.example.json
    goarch: arm64

# Multi-arch Docker manifests
docker_manifests:
  - name_template: 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:{{.Version}}'
    image_templates:
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:{{.Version}}-amd64'
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:{{.Version}}-arm64'
  - name_template: 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:latest'
    image_templates:
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:latest-amd64'
      - 'ghcr.io/the-permaweb-harlequin/harlequin-remote-signing:latest-arm64'

# Skip GitHub Release (handled by Nx Release)
release:
  disable: true
